using DenariusAI.Infrastructure.Identity;
using DenariusAI.Domain.Entities;
using DenariusAI.Domain.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.Json;

namespace DenariusAI.Infrastructure.Persistence;

/// <summary>Database context for the Denarius AI application.</summary>
public sealed class DenariusDbContext(DbContextOptions<DenariusDbContext> options, IHttpContextAccessor? httpContextAccessor = null) : IdentityDbContext<ApplicationUser>(options)
{
    public bool SuppressAudit { get; set; }
    public DbSet<FinancialGroup> FinancialGroups => Set<FinancialGroup>(); public DbSet<Category> Categories => Set<Category>(); public DbSet<Account> Accounts => Set<Account>(); public DbSet<JournalEntry> JournalEntries => Set<JournalEntry>(); public DbSet<JournalEntryLine> JournalEntryLines => Set<JournalEntryLine>(); public DbSet<Budget> Budgets => Set<Budget>(); public DbSet<BudgetLine> BudgetLines => Set<BudgetLine>(); public DbSet<Reconciliation> Reconciliations => Set<Reconciliation>(); public DbSet<ApplicationSetting> ApplicationSettings => Set<ApplicationSetting>(); public DbSet<SavingsCertificate> SavingsCertificates => Set<SavingsCertificate>(); public DbSet<StockPosition> StockPositions => Set<StockPosition>(); public DbSet<StockPrice> StockPrices => Set<StockPrice>(); public DbSet<Reminder> Reminders => Set<Reminder>(); public DbSet<ReminderAcknowledgement> ReminderAcknowledgements => Set<ReminderAcknowledgement>(); public DbSet<Warranty> Warranties => Set<Warranty>(); public DbSet<Correspondence> Correspondence => Set<Correspondence>(); public DbSet<CorrespondenceMetadata> CorrespondenceMetadata => Set<CorrespondenceMetadata>(); public DbSet<AuditLog> AuditLogs => Set<AuditLog>(); public DbSet<LoginHistory> LoginHistory => Set<LoginHistory>();

    /// <summary>Configures the model and entity relationships.</summary><param name="builder">The model builder.</param>
    protected override void OnModelCreating(ModelBuilder builder) { base.OnModelCreating(builder); builder.HasDefaultSchema("denarius"); builder.ApplyConfigurationsFromAssembly(typeof(DenariusDbContext).Assembly); }
    /// <summary>Saves changes after applying auditing and accounting validation.</summary><param name="cancellationToken">Cancellation token.</param><returns>The number of written entries.</returns>
    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default) { ApplyAuditTimestamps(); ValidateJournalEntries(); CaptureAuditLogs(); return base.SaveChangesAsync(cancellationToken); }
    /// <summary>Captures audit records for tracked changes.</summary>
    private void CaptureAuditLogs() { if (SuppressAudit) return; var entries=ChangeTracker.Entries().Where(e=>e.Entity is not AuditLog && e.State is EntityState.Added or EntityState.Modified or EntityState.Deleted && (e.Entity is AuditableEntity || e.Entity is ApplicationUser or ReminderAcknowledgement)).ToList(); if(entries.Count==0)return; var principal=httpContextAccessor?.HttpContext?.User; var userId=principal?.FindFirstValue(ClaimTypes.NameIdentifier); var userName=principal?.Identity?.Name; var now=DateTimeOffset.UtcNow; foreach(var entry in entries){var key=string.Join("|",entry.Properties.Where(p=>p.Metadata.IsPrimaryKey()).Select(p=>(entry.State==EntityState.Deleted?p.OriginalValue:p.CurrentValue)?.ToString())); if(string.IsNullOrWhiteSpace(key))continue; var oldValues=new SortedDictionary<string,object?>(); var newValues=new SortedDictionary<string,object?>(); var changed=new List<string>(); foreach(var property in entry.Properties){if(IsSensitive(property.Metadata.Name)){if(entry.State==EntityState.Modified&&property.IsModified&&!Equals(property.OriginalValue,property.CurrentValue))changed.Add(property.Metadata.Name);continue;} if(entry.State is EntityState.Modified or EntityState.Deleted)oldValues[property.Metadata.Name]=property.OriginalValue;if(entry.State is EntityState.Added or EntityState.Modified)newValues[property.Metadata.Name]=property.CurrentValue;if(entry.State==EntityState.Modified&&property.IsModified&&!Equals(property.OriginalValue,property.CurrentValue))changed.Add(property.Metadata.Name);} if(entry.State==EntityState.Modified&&changed.Count==0)continue; var action=entry.State switch{EntityState.Added=>"Created",EntityState.Modified=>"Updated",_=>"Deleted"}; var values=entry.State==EntityState.Deleted?oldValues:newValues; AuditLogs.Add(new AuditLog{EntityType=entry.Metadata.ClrType.Name,EntityId=key,RecordLabel=FindLabel(values,key),Action=action,ChangedAt=now,UserId=userId??FindActor(entry,action),UserName=userName,ChangedColumns=changed.Count==0?null:JsonSerializer.Serialize(changed),OldValues=oldValues.Count==0?null:JsonSerializer.Serialize(oldValues),NewValues=newValues.Count==0?null:JsonSerializer.Serialize(newValues)});}}
    /// <summary>Determines whether an audited property is sensitive.</summary><param name="name">Property name.</param><returns>True for sensitive properties.</returns>
    private static bool IsSensitive(string name)=>name is "PasswordHash" or "SecurityStamp" or "ConcurrencyStamp" or "AuthenticatorKey" or "Value" or "ProfileImageBase64" or "DocumentBase64";
    /// <summary>Finds the actor recorded on an auditable entity.</summary><param name="entry">Tracked entry.</param><param name="action">Audit action.</param><returns>The actor identifier.</returns>
    private static string? FindActor(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry entry,string action)=>entry.Properties.FirstOrDefault(p=>p.Metadata.Name==(action=="Created"?"CreatedBy":"UpdatedBy"))?.CurrentValue?.ToString()??"system";
    /// <summary>Finds a readable label for an audited record.</summary><param name="values">Record values.</param><param name="fallback">Fallback label.</param><returns>A readable label.</returns>
    private static string FindLabel(IReadOnlyDictionary<string,object?> values,string fallback){foreach(var name in new[]{"Name","Ticker","Subject","DisplayName","Description","Text","Email","SeriesNumber","Reference","Key","Date"})if(values.TryGetValue(name,out var value)&&!string.IsNullOrWhiteSpace(value?.ToString()))return value!.ToString()!;return fallback;}
    /// <summary>Applies audit timestamps to auditable entities.</summary>
    private void ApplyAuditTimestamps(){var now=DateTimeOffset.UtcNow;foreach(var trackedEntry in ChangeTracker.Entries<AuditableEntity>()){if(trackedEntry.State==EntityState.Added&&trackedEntry.Entity.CreatedAt==default)trackedEntry.Entity.CreatedAt=now;if(trackedEntry.State==EntityState.Modified)trackedEntry.Entity.UpdatedAt=now;}}
    /// <summary>Validates changed journal entries.</summary>
    private void ValidateJournalEntries(){var entries=ChangeTracker.Entries<JournalEntry>().Where(e=>e.State is EntityState.Added or EntityState.Modified).Select(e=>e.Entity).Concat(ChangeTracker.Entries<JournalEntryLine>().Where(e=>e.State is EntityState.Added or EntityState.Modified or EntityState.Deleted).Select(e=>e.Entity.JournalEntry)).Where(e=>e is not null).Distinct();foreach(var entry in entries)entry.EnsureBalanced();}
}
