version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 3
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns: ["*"]
