// <auto-generated />
using System;
using DenariusAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenariusAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DenariusDbContext))]
    [Migration("20260905144328_NormalizeDemonstrationSeedOwnership")]
    partial class NormalizeDemonstrationSeedOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("denarius")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Accounts", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Currency", "LEN([Currency]) = 3");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("Budgets", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_Budgets_Month", "[Month] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_Budgets_Year", "[Year] BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique();

                    b.ToTable("BudgetLines", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetLines_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FinancialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialGroupId");

                    b.HasIndex("FinancialGroupId", "Name")
                        .IsUnique();

                    b.HasIndex("FinancialGroupId", "SortOrder");

                    b.ToTable("Categories", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Conta à Ordem",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Conta Poupança",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Investimentos",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Dinheiro",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Salário",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Subsídios",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Pensões",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Trabalhos ocasionais",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Reembolsos",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Prémios",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Habitação",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Água",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Electricidade",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Alimentação",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Transportes",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Saúde",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Educação",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Seguros",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Lazer",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Subscrições",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000050"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Viagens",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000051"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Reparações",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000052"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Equipamentos",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000053"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Compras extraordinárias",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000001100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Constituição de Poupanças",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com a casa",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004200"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com o carro e transportes",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004300"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas Bancárias e Seguros",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004400"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com o Estado e Impostos",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004500"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com Compras",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004600"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com cuidados pessoais",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004700"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com Estudo e Formação",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004800"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Caixas e Fundo de Maneio",
                            SortOrder = 18
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Correspondence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("Sender")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedDate");

                    b.ToTable("Correspondence", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.CorrespondenceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Confidence")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CorrespondenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CorrespondenceId");

                    b.HasIndex("CorrespondenceId", "Key")
                        .IsUnique();

                    b.ToTable("CorrespondenceMetadata", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.FinancialGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("FinancialGroups", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 1,
                            Name = "Património e Poupanças",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 2,
                            Name = "Rendimentos Correntes",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 2,
                            Name = "Rendimentos Extra",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 3,
                            Name = "Despesas Correntes",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 3,
                            Name = "Despesas Extra",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InsuredSubject")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Insurer")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("int");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber");

                    b.HasIndex("RenewalDate");

                    b.ToTable("InsurancePolicies", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePolicyAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("InsurancePolicyAttachments", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePremium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("PolicyId");

                    b.ToTable("InsurancePremiums", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePremiumAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PremiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PremiumId");

                    b.ToTable("InsurancePremiumAttachments", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("Date");

                    b.HasIndex("Status", "Date");

                    b.ToTable("JournalEntries", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_JournalEntryLines_DebitCredit", "([Debit] > 0 AND [Credit] = 0) OR ([Credit] > 0 AND [Debit] = 0)");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReconciledBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Reconciliations", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("NoticeDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("SavingsCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("SavingsCertificateId")
                        .IsUnique()
                        .HasFilter("[SavingsCertificateId] IS NOT NULL");

                    b.HasIndex("WarrantyId")
                        .IsUnique()
                        .HasFilter("[WarrantyId] IS NOT NULL");

                    b.ToTable("Reminders", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.ReminderAcknowledgement", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReminderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ReminderAcknowledgements", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.SavingsCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("InvestmentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InvestmentValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateOnly>("NextCapitalization")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("SeriesNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentDate");

                    b.HasIndex("SeriesNumber")
                        .IsUnique();

                    b.ToTable("SavingsCertificates", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.StockPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageCost")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ForecastEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("HistoryStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("WatchlistOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Exchange")
                        .IsUnique()
                        .HasFilter("[Exchange] IS NOT NULL");

                    b.ToTable("StockPositions", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.StockPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<Guid>("StockPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockPositionId", "Date")
                        .IsUnique();

                    b.ToTable("StockPrices", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.ToTable("Warranties", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CookieConsentAcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DemonstrationDataAcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowAssetBalancesWidget")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Persistence.ApplicationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Persistence.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Action", "ChangedAt");

                    b.HasIndex("UserId", "ChangedAt");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.ToTable("AuditLogs", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Persistence.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LoggedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedInAt");

                    b.ToTable("LoginHistory", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("Accounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.BudgetLine", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Budget", "Budget")
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("BudgetLines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.FinancialGroup", "FinancialGroup")
                        .WithMany("Categories")
                        .HasForeignKey("FinancialGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinancialGroup");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.CorrespondenceMetadata", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Correspondence", "Correspondence")
                        .WithMany("Metadata")
                        .HasForeignKey("CorrespondenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correspondence");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePolicyAttachment", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.InsurancePolicy", "Policy")
                        .WithMany("Attachments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePremium", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DenariusAI.Domain.Entities.InsurancePolicy", "Policy")
                        .WithMany("Premiums")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePremiumAttachment", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.InsurancePremium", "Premium")
                        .WithMany("Attachments")
                        .HasForeignKey("PremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premium");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntry", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Budget", "Budget")
                        .WithMany("JournalEntries")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntryLine", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DenariusAI.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reconciliation", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithOne("Reconciliation")
                        .HasForeignKey("DenariusAI.Domain.Entities.Reconciliation", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.SavingsCertificate", "SavingsCertificate")
                        .WithOne("Reminder")
                        .HasForeignKey("DenariusAI.Domain.Entities.Reminder", "SavingsCertificateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DenariusAI.Domain.Entities.Warranty", "Warranty")
                        .WithOne("Reminder")
                        .HasForeignKey("DenariusAI.Domain.Entities.Reminder", "WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SavingsCertificate");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.ReminderAcknowledgement", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Reminder", "Reminder")
                        .WithMany("Acknowledgements")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.StockPrice", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.StockPosition", "StockPosition")
                        .WithMany()
                        .HasForeignKey("StockPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockPosition");
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Persistence.LoginHistory", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Budget", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetLines");

                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Correspondence", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.FinancialGroup", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePolicy", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Premiums");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.InsurancePremium", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Reconciliation");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reminder", b =>
                {
                    b.Navigation("Acknowledgements");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.SavingsCertificate", b =>
                {
                    b.Navigation("Reminder")
                        .IsRequired();
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Warranty", b =>
                {
                    b.Navigation("Reminder")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
