// <auto-generated />
using System;
using DenariusAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenariusAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DenariusDbContext))]
    [Migration("20260824125524_DemonstrationFinancialScenario")]
    partial class DemonstrationFinancialScenario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("denarius")
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Accounts", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Currency", "LEN([Currency]) = 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AccountType = 1,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            Description = "Conta bancária principal do cenário de demonstração.",
                            InitialBalance = 0m,
                            IsActive = true,
                            Name = "Conta à Ordem — Demonstração"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AccountType = 3,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            Description = "Poupança familiar do cenário de demonstração.",
                            InitialBalance = 500m,
                            IsActive = true,
                            Name = "Conta Poupança — Demonstração"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AccountType = 2,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            Description = "Carteira de numerário do cenário de demonstração.",
                            InitialBalance = 100m,
                            IsActive = true,
                            Name = "Dinheiro — Demonstração"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AccountType = 7,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            Description = "Contrapartida contabilística dos rendimentos.",
                            InitialBalance = 0m,
                            IsActive = true,
                            Name = "Rendimentos — Demonstração"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AccountType = 8,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            Description = "Contrapartida contabilística das despesas.",
                            InitialBalance = 0m,
                            IsActive = true,
                            Name = "Despesas — Demonstração"
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("Budgets", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_Budgets_Month", "[Month] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_Budgets_Year", "[Year] BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique();

                    b.ToTable("BudgetLines", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetLines_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FinancialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialGroupId");

                    b.HasIndex("FinancialGroupId", "Name")
                        .IsUnique();

                    b.HasIndex("FinancialGroupId", "SortOrder");

                    b.ToTable("Categories", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Conta à Ordem",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Conta Poupança",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Investimentos",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Dinheiro",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Salário",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Subsídios",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Pensões",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Trabalhos ocasionais",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Reembolsos",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Prémios",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Habitação",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Água",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Electricidade",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Alimentação",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Transportes",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Saúde",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Educação",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Seguros",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Lazer",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Subscrições",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000050"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Viagens",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000051"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Reparações",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000052"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Equipamentos",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000053"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "Compras extraordinárias",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000001100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Constituição de Poupanças",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com a casa",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004200"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com o carro e transportes",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004300"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas Bancárias e Seguros",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004400"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com o Estado e Impostos",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004500"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com Compras",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004600"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com cuidados pessoais",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004700"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Despesas com Estudo e Formação",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000004800"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FinancialGroupId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Caixas e Fundo de Maneio",
                            SortOrder = 18
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.FinancialGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("FinancialGroups", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 1,
                            Name = "Património e Poupanças",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 2,
                            Name = "Rendimentos Correntes",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 2,
                            Name = "Rendimentos Extra",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 3,
                            Name = "Despesas Correntes",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Kind = 3,
                            Name = "Despesas Extra",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status", "Date");

                    b.ToTable("JournalEntries", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 1),
                            Description = "Salário mensal",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "REC-JUL-001",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 3),
                            Description = "Renda da casa",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "PAG-JUL-001",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 5),
                            Description = "Compras de supermercado",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "TALAO-1842",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 7),
                            Description = "Fatura de eletricidade",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "ELEC-0726",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 8),
                            Description = "Fatura de água",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "AGUA-0726",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 10),
                            Description = "Transferência para poupança",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "TRF-POUP",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 12),
                            Description = "Levantamento ATM",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "ATM-1208",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 15),
                            Description = "Jantar em família",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "REST-1508",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 18),
                            Description = "Trabalho ocasional",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "FREELANCE-07",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Date = new DateOnly(2026, 7, 20),
                            Description = "Viagem de verão",
                            Notes = "Dados de demonstração — julho 2026",
                            Reference = "VIAGEM-2026",
                            Status = 1
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines", "denarius", t =>
                        {
                            t.HasCheckConstraint("CK_JournalEntryLines_DebitCredit", "([Debit] > 0 AND [Credit] = 0) OR ([Credit] > 0 AND [Debit] = 0)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 2500m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 2500m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 750m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 750m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 180m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 180m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 65m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 65m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 32m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 32m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 300m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000012"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000001100"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 300m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000013"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 100m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000014"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 100m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000015"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 80m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000016"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 80m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000017"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 350m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000018"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 350m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000019"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000050"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 0m,
                            Debit = 450m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000020"),
                            AccountId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            Credit = 450m,
                            Debit = 0m,
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReconciledBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Reconciliations", "denarius");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ReconciledAt = new DateTimeOffset(new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReconciledBy = "demo-seed",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ReconciledAt = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReconciledBy = "demo-seed",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ReconciledAt = new DateTimeOffset(new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReconciledBy = "demo-seed",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "demo-seed",
                            JournalEntryId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ReconciledAt = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReconciledBy = "demo-seed",
                            Status = 2
                        });
                });

            modelBuilder.Entity("DenariusAI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "denarius");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "denarius");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("Accounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.BudgetLine", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Budget", "Budget")
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("BudgetLines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.FinancialGroup", "FinancialGroup")
                        .WithMany("Categories")
                        .HasForeignKey("FinancialGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinancialGroup");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntryLine", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenariusAI.Domain.Entities.Category", "Category")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DenariusAI.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Reconciliation", b =>
                {
                    b.HasOne("DenariusAI.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithOne("Reconciliation")
                        .HasForeignKey("DenariusAI.Domain.Entities.Reconciliation", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DenariusAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Account", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetLines");

                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.FinancialGroup", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DenariusAI.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Reconciliation");
                });
#pragma warning restore 612, 618
        }
    }
}
