<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DenariusAI.Application/DenariusAI.Application.csproj" />
    <ProjectReference Include="../DenariusAI.Infrastructure/DenariusAI.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>
</Project>
